#pragma once

#include <everest/types/uint32/bit_and.h>
#include <everest/types/uint32/bit_or.h>
#include <everest/types/uint32/bit_xor.h>
#include <everest/types/uint32/bounded.h>
#include <everest/types/uint32/copyable.h>
#include <everest/types/uint32/divide.h>
#include <everest/types/uint32/eq.h>
#include <everest/types/uint32/fundamental.h>
#include <everest/types/uint32/hashable.h>
#include <everest/types/uint32/hexable.h>
#include <everest/types/uint32/monoid.h>
#include <everest/types/uint32/multiply.h>
#include <everest/types/uint32/one.h>
#include <everest/types/uint32/ord.h>
#include <everest/types/uint32/remainder.h>
#include <everest/types/uint32/semigroup.h>
#include <everest/types/uint32/show.h>
#include <everest/types/uint32/subtract.h>
#include <everest/types/uint32/zero.h>
