language: cpp
compiler:
  - gcc
os:
  - osx
before_install:
  - brew update
  - brew install homebrew/versions/gcc6
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
script: make test
