#pragma once

#include <everest/containers/option/containable.h>
#include <everest/containers/option/container.h>
#include <everest/containers/option/alternative.h>
#include <everest/containers/option/eq.h>
#include <everest/containers/option/foldable.h>
#include <everest/containers/option/functor.h>
#include <everest/containers/option/hashable.h>
#include <everest/containers/option/iteration.h>
#include <everest/containers/option/monad.h>
#include <everest/containers/option/semigroup.h>
#include <everest/containers/option/zero.h>
#include <everest/containers/option/monoid.h>
#include <everest/containers/option/filterable.h>
#include <everest/containers/option/ord.h>
#include <everest/containers/option/monad_plus.h>
#include <everest/containers/option/unwrappable.h>
#include <everest/containers/option/shows.h>