#pragma once

#include <everest/types/int64/bit_and.h>
#include <everest/types/int64/bit_or.h>
#include <everest/types/int64/bit_xor.h>
#include <everest/types/int64/bounded.h>
#include <everest/types/int64/copyable.h>
#include <everest/types/int64/divide.h>
#include <everest/types/int64/eq.h>
#include <everest/types/int64/fundamental.h>
#include <everest/types/int64/hashable.h>
#include <everest/types/int64/hexable.h>
#include <everest/types/int64/monoid.h>
#include <everest/types/int64/multiply.h>
#include <everest/types/int64/negate.h>
#include <everest/types/int64/one.h>
#include <everest/types/int64/ord.h>
#include <everest/types/int64/remainder.h>
#include <everest/types/int64/semigroup.h>
#include <everest/types/int64/show.h>
#include <everest/types/int64/square_root.h>
#include <everest/types/int64/subtract.h>
#include <everest/types/int64/zero.h>
